version: "3"
services:

  nginx:
    image: "seokjoon/all:ami.wcms.v3.2"
    deploy:
      replicas: 3
      # placement:
        # constraints: [node.role != manager]
        # constraints: [node.role == manager]
        # constraints:
          # - node.role == manager
    ports:
      - 80:80
    networks:
      - wcms-net
    volumes:
      - nginx_conf:/etc/nginx/ssl
      - nginx_log:/var/log/nginx
      - nginx_www:/var/www

#  mysql:
#    image: mysql:5.7
#    ports:
#      - 3306:3306
#    networks:
#      - wcms-net
#    command:
#      - "--max_allowed_packet=128M"
#      - "--innodb_buffer_pool_size=128M"
#      - "--wait_timeout=3600"
#      - "--interactive_timeout=3600"
#      - "--connect_timeout=600"
#      - "--net_read_timeout=600"
#      - "--net_write_timeout=600"
#    volumes:
#      - mysql_conf:/etc/mysql/conf.d
#      - mysql_data:/var/lib/mysql
#      - mysql_log:/var/log/mysql

  cp:
    image: alpine
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [node.role == manager]
    command: tail -f /dev/null
    networks:
      - wcms-net
    volumes:
      - nginx_conf:/etc/nginx/ssl
      - nginx_log:/var/log/nginx
      - nginx_www:/var/www
      - mysql_conf:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql

volumes:
  mysql_conf:
  mysql_data:
  mysql_log:
  nginx_conf:
  nginx_log:
  nginx_www:

networks:
  wcms-net:
    external: true