version: "3"
services:

  registry:
    container_name: registry
    image: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - "/d1/infra/docker/registry:/var/lib/registry"